{% set name = "aws-sdk-core" %}
{% set version = "3.1.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 10feedf34d1b2f376536e5ce715e8b7de5a16d34a55c6c395fce0816b73f143a

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-aws-sigv4 >=1.0,<2
    - rb-jmespath >=1.0,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Provides API clients for AWS. This gem is part of the official AWS SDK for Ruby

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/aws/aws-sdk-ruby

extra:
  recipe-maintainers:
    - conda-forge/ruby
    - pierrsc
