travis:
  secure:
    BINSTAR_TOKEN: X83vH5I5W79LIwSQ1/DoyKO6etO1qzWLxLhLn+IoshBrYBCyjYE9fcmb+hafaEcfr8Tx4I1qN0mRdo0szYaohUB2M9eQMt5W4QGZaRmhXG73dLfl/8X4xPJ4g9AvYeYMkJo34/cE47xfiQP3BnWkKNthILI8OlTnQx8NPVSmjlPgO2brYCGPQvGaNPLPl3YZovYaJqr4cGzDQl3taezohyubX50F7AMp1l8J9ArKNz9AhBMS2jHB+K8BifSvX0jrzimPIzymL9MxuWjXSvRqVZ1KFxNHhviiV9Rg36KkGiHqGDKSyXyW5WQnL4zVk0vmRs0jCdLmOLz6oXFPIAPuMw4H8qlu1QSxe76sxUdQ+EOOzMfN4sGOagXe1a1RbKJ71JOmx+/AUfSzBCnNqTge0IYfZfnPxxhEO2ewk5AqH88/+fXrncvCv1dhAL9TX9cxw1DjaTohP8jiSciBB8YPMxuyisSLVAeHaBv2vnJOBiyRRARfzUJ6UpTtxJB7PSy6MuinnYVCAoRN4i76IDOCuCawLUTXSk+FsEkB8hlJRWntSAqvUXgOQHobiqa7sULRIbgqu2aUSDKNuJHV+LMrI7W0PJaxcUXVnPWU0GoWhr45hzR8sAkgw9BRBLloJlau+iAnkDqQS63hmT8k1oPQfU9CObM0hYyLJPgOt0tbMyU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
